### ISSUE TITLE
无法使用latest标签或akshare的最新版本号1.9.43启动docker容器

### ISSUE THREAD

**Issue by alexcdever** [akfamily/aktools#131]
我根据文档写了一份docker-compose.yml文件，想用最新版本的镜像，但启动失败。根据文档描述，镜像的版本号是akshare的版本号,我接着用1.9.43，不行，然后用低一版本1.9.42，可以了。
以下是我的docker-compose.yml：
``` yaml
version: '3.7'

services:
  datasource:
    container_name: aktools
    image: registry.cn-shanghai.aliyuncs.com/akfamily/aktools:1.9.42
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8080:8080

```
